coding_task:
  description: >
    Escreva código Python para realizar isto: {assignment}
  expected_output: >
    Um arquivo de texto que inclua o próprio código, junto com a saída do código.
  agent: coder
  output_file: output/code_and_output.txt